site_name: Nova Documentation
site_author: Kiran D
repo_url: https://github.com/Larkify/nova-docs/
repo_name: larkify/nova-docs

theme: 
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png

  font: 
    text: Segoe UI

  plugins:
    - git-revision-date:
        enabled_if_env: CI
    - search: 
        en

  icon:
    repo: fontawesome/brands/github-alt
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top

extra: 
    social:
    ## github
    - icon: fontawesome/brands/github
      link: https://github.com/larkify
    ## discord server
    - icon: fontawesome/brands/discord
      link: https://larkx.xyz/discord
    ## email me
    - icon: fontawesome/solid/at
      link: mailto:contact@larkx.xyz

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - meta

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Configuration: sections/configuration.md
  - Image: sections/image.md
  - Information: sections/information.md
  - Miscellaneous: sections/miscellaneous.md
  - Moderator: sections/moderator.md
  - Suggestions: sections/suggestions.md
  - Tags: sections/tags.md
