site_name: Nova Documentation
site_author: Kiran D
repo_url: https://github.com/Larkify/nova-docs/
repo_name: larkify/nova-docs

theme: 
  name: material

  plugins:
    - git-revision-date:
        enabled_if_env: CI
    - search: 
        en

  icon:
    repo: fontawesome/brands/github-alt
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
  icon:
    logo: logo

extra: 
    social:
    ## github
    - icon: fontawesome/brands/github
      link: https://github.com/larkify
    ## discord server
    - icon: fontawesome/brands/discord
      link: https://larkx.xyz/discord
    ## email me
    - icon: fontawesome/solid/at
      link: mailto:contact@larkx.xyz

nav:
  - Home: index.md
  - Configuration:
    - Installation: getting-started.md
    - Creating your site: creating-your-site.md
    - Publishing your site: publishing-your-site.md
    - Customization: customization.md
    - Troubleshooting: troubleshooting.md
    - Data privacy: data-privacy.md
    - License: license.md
    - Releases:
      - Changelog: changelog.md
      - Upgrade guide: upgrading.md
      - Deprecations: deprecations.md
  - Setup:
    - Changing the colors: setup/changing-the-colors.md
    - Changing the fonts: setup/changing-the-fonts.md
    - Changing the language: setup/changing-the-language.md
    - Changing the logo and icons: setup/changing-the-logo-and-icons.md
    - Setting up navigation: setup/setting-up-navigation.md
    - Setting up site search: setup/setting-up-site-search.md
    - Setting up site analytics: setup/setting-up-site-analytics.md
    - Setting up social cards: setup/setting-up-social-cards.md
    - Setting up tags: setup/setting-up-tags.md
    - Setting up versioning: setup/setting-up-versioning.md
    - Setting up the header: setup/setting-up-the-header.md
    - Setting up the footer: setup/setting-up-the-footer.md
    - Adding a git repository: setup/adding-a-git-repository.md
    - Adding a comment system: setup/adding-a-comment-system.md
  - Reference:
    - Abbreviations: reference/abbreviations.md
    - Admonitions: reference/admonitions.md
    - Buttons: reference/buttons.md
    - Code blocks: reference/code-blocks.md
    - Content tabs: reference/content-tabs.md
    - Data tables: reference/data-tables.md
    - Diagrams: reference/diagrams.md
    - Footnotes: reference/footnotes.md
    - Formatting: reference/formatting.md
    - Icons + Emojis: reference/icons-emojis.md
    - Images: reference/images.md
    - Lists: reference/lists.md
    - MathJax: reference/mathjax.md
    - Meta tags: reference/meta-tags.md
    - Variables: reference/variables.md
  - Insiders:
    - Sponsorship: insiders/index.md
    - Getting started:
      - Installation: insiders/getting-started.md
      - Changelog: insiders/changelog.md
